### ISSUE TITLE
ZeptoForth compatibility?

### ISSUE THREAD

**Issue by extrowerk** [ryonlabaw/rp2040-pHAT#1]
Hi,

I have found your board on tindie, but because the high shipping costs, I would like to know first if it is comptible with my use-case. Could you please test your board with the latest Zeptoforth build? It should be freely available here: https://github.com/tabemann/zeptoforth/releases
Theoretically it should run just fine, possibly the bigger flash won't be used automatically, but that would be just a matter of a minimal patching.

Thank You!

**Comment by extrowerk** [comment]
Also could you provide a 3d model or a drawing about your board so we can incorporate it in our projects?

**Comment by ryonlabaw** [comment]
OK, I don't see any reason why zeptoforth would not work. The rp2040-pHat
board is a basic implementation of the rp2040.
I'm kinda busy right now, so I don't have time to set up and test
zeptoforth.

What country are you wanting to ship to?
How many units?
Let me know and perhaps we can work something out.

I can provide an OBJ file, a DXF file and PDF drawing/measurements of the
board.

**Comment by extrowerk** [comment]
I am located in Hungary / central EU, I need 2 unit only.

I would greatly appreciate if you could upload the OBJ and a PDF drawing so I can design my enclosure around it..

**Comment by ryonlabaw** [comment]
Added some files to the docs folder
https://github.com/ryonlabaw/rp2040-pHAT/tree/main/docs

let me know if you need anything else.

**Comment by extrowerk** [comment]
Thank You!
I am on my way to build a small device, and your board seems to be the perfect choice. Sadly the OBJ you just posted seems to be somewhat non-accurate: it shows pin-headers which is not shown on the photos. Also it missing some components (rp2040 for example). I am also not exactly sure if there is any components mounted on the bottom side of the PCB. Could you please provide me some info?

Regarding the buttons : is it possible to remove / replace them with a smaller one, or using jumper wires if necessary? I am not from EE, so I naively think it should be possible, but would be nice if you could confirm. Thank You!

**Comment by ryonlabaw** [comment]
Not sure why the headers are being exported as a component. The EDA design app used for this board doesn't give an option to customize the exported components.  Maybe its possible to modify the model in your 3d design software?
Here is a version with just the pcb.
https://github.com/ryonlabaw/rp2040-pHAT/blob/main/docs/pcb-only-3d-obj.zip

The buttons are used for re/programming from the usb port. 
I would need to know more about your final setup/design to be able to say if you will have success without the buttons.
Maybe, if you upload the code first, then you could remove the buttons.

Are you connecting this device to a raspberry pi?

**Comment by ryonlabaw** [comment]
Regarding replacing buttons with jumpers or wires... yes, that is doable. 
Just note that the boot button is used momentarily, at bootup. Then it is not used.
Reset button can be used at any time, but is not required. Its momentary as well.
So the jumper/wire would need to be connected and disconnected.

**Comment by extrowerk** [comment]
Thanks for  the info. The sw i plan to use is Zeptoforth, and from my understanding i can safely remove the switches after uploading it.
I am working on a small, forth based programming handheld. There is no rpi involved. Instead of that Zeptoforth provides a REPL command-line interface over UART, so I simply connect a dumb terminal (which consist a keyboard + a lcd display) to be able to interact with Zeptoforth on the road and control the GPIO without needing any computer.

I recommend you to try Zeptoforth: it is interesting and can communicate via UART over USB aswell (CDC i think), so you can upload the uf2, then connect to the REPL via terminal over USB.

**Comment by extrowerk** [comment]
Thanks for al lthe info you provided already. I am wondering if you could publish a bit better schematics. The [current one](https://github.com/ryonlabaw/rp2040-pHAT/blob/main/docs/schematic.png) is not readable, at least not for my bad eyes. Thanks!

**Comment by ryonlabaw** [comment]
Here is a pdf version
https://github.com/ryonlabaw/rp2040-pHAT/blob/main/docs/schematic.pdf

**Comment by extrowerk** [comment]
I have received the boards, but you have made a big mistake, I have ordered 2 boards but received 5!

I have just tested it, zeptoforth boots just fine on your pHAT!

**Comment by ryonlabaw** [comment]
No mistake. I am just generous to my customers, enjoy.
